 


# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PedometerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for PedometerApp
  pod 'Firebase/Core'
  pod 'Firebase/Messaging', '~> 5.20.1'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'
  pod 'GoogleSignIn'

end
